log:
  project_name: 'deepar_original'
  run_name: 'exp_7'
  log_path: './logs'

results:
  results_path: './results'

data:
  data_type: 'original'  # original, corelation, time
  file_path: './data/data.csv'
  prediction_length: 24
  train_cutoff: 9119
  val_cutoff: 10271
  total_num: 11423
  window_size: 168
  shift: 1
  cor_threshold: 0.5

model:
  
train:
  seed: 3407
  gpu_index: 0

val:
  batch_size: 32

test:
  batch_size: 32